name: "inaam"

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ../apps/server
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ../apps/server:/app
      - /app/.venv
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:password@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ../apps/client
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ../apps/client:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://localhost:8000
    depends_on:
      - server

volumes:
  postgres_data:
