"""add_task_type_to_tasks

Revision ID: 02ddb3c83275
Revises: ba779cb42b1d
Create Date: 2026-05-13 22:12:09.022610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ddb3c83275'
down_revision: Union[str, Sequence[str], None] = 'ba779cb42b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BOUNTY', 'OBJECTIVE', name='tasktype').create(op.get_bind())
    # Add as nullable first to handle existing data
    op.add_column('tasks', sa.Column('task_type', sa.Enum('BOUNTY', 'OBJECTIVE', name='tasktype'), nullable=True))
    
    # Data migration: set task_type based on reward_id
    op.execute("UPDATE tasks SET task_type = 'BOUNTY' WHERE reward_id IS NULL")
    op.execute("UPDATE tasks SET task_type = 'OBJECTIVE' WHERE reward_id IS NOT NULL")
    
    # Set to NOT NULL after data is populated
    op.alter_column('tasks', 'task_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_type')
    sa.Enum('BOUNTY', 'OBJECTIVE', name='tasktype').drop(op.get_bind())
    # ### end Alembic commands ###
