"""add_recurring_task_fields_optional

Revision ID: 04a077ae8878
Revises: 7deccecb3d81
Create Date: 2026-05-19 13:08:54.762264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a077ae8878'
down_revision: Union[str, Sequence[str], None] = '7deccecb3d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_days', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence_days')
    op.drop_column('tasks', 'is_recurring')
    # ### end Alembic commands ###
