"""remove_quests_objectives

Revision ID: 1e73b3a41e01
Revises: 8d64949ba26a
Create Date: 2026-05-27 21:44:30.380405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e73b3a41e01'
down_revision: Union[str, Sequence[str], None] = '8d64949ba26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Data Migration: Ensure Quests have 0 cost_points so they remain free to claim
    op.execute("UPDATE rewards SET cost_points = 0 WHERE reward_type = 'QUEST'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'reward_type')
    op.drop_constraint(op.f('tasks_reward_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'task_type')
    op.drop_column('tasks', 'reward_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reward_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('task_type', postgresql.ENUM('BOUNTY', 'OBJECTIVE', name='tasktype'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tasks_reward_id_fkey'), 'tasks', 'rewards', ['reward_id'], ['id'], ondelete='CASCADE')
    op.add_column('rewards', sa.Column('reward_type', postgresql.ENUM('QUEST', 'PRIZE', name='reward_type_v2'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
