"""make_is_recurring_not_null

Revision ID: 25622824a8ff
Revises: 04a077ae8878
Create Date: 2026-05-19 13:10:49.838633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25622824a8ff'
down_revision: Union[str, Sequence[str], None] = '04a077ae8878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
