"""enforce_non_null_user_progress

Revision ID: 6675cb803147
Revises: ef992e352889
Create Date: 2026-05-29 22:29:25.136254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6675cb803147'
down_revision: Union[str, Sequence[str], None] = 'ef992e352889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_progress', 'active_rank',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user_progress', 'lifetime_xp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_progress', 'spendable_points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_progress', 'total_tasks_completed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_progress', 'perfect_weeks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_progress', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_progress', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_progress', 'perfect_weeks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_progress', 'total_tasks_completed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_progress', 'spendable_points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_progress', 'lifetime_xp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_progress', 'active_rank',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
