"""make_pinned_column_not_null

Revision ID: 8d64949ba26a
Revises: 55805613d7af
Create Date: 2026-05-22 16:09:48.306100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d64949ba26a'
down_revision: Union[str, Sequence[str], None] = '55805613d7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
